### ISSUE TITLE
Revert back /pricing URLs

### ISSUE THREAD

**Issue by eistrati** [404md/www#112]
Because of SEO considerations, revert back /pricing & /ro/pricing & /ru/pricing because they are already indexed by Google and others.

**Comment by avozicov** [comment]
Test Failed.
Please refer to attachment for more details:
<img width="1280" alt="screen shot 2017-05-15 at 12 40 37" src="https://cloud.githubusercontent.com/assets/12330493/26051733/bfcfb8b6-396b-11e7-934e-8c3db73f0c72.png">

**Comment by tkaciuk** [comment]
Tested.
