### ISSUE TITLE
Create Startup-evening page + responsive

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#118]
https://xd.adobe.com/view/760f8339-f244-40ce-907e-437947de58b4/

**Comment by avozicov** [comment]
Test for Responsive design for "Startup-evening" page - Failed.

_Please refer to attachment for more details_
<img width="1280" alt="screen shot 2017-05-15 at 13 51 37" src="https://cloud.githubusercontent.com/assets/12330493/26054619/f00bcf06-3975-11e7-93af-4f2bc6556f7a.png">
<img width="1280" alt="screen shot 2017-05-15 at 13 51 40" src="https://cloud.githubusercontent.com/assets/12330493/26054618/f00c30cc-3975-11e7-9b0a-361a624727b2.png">

**Comment by avozicov** [comment]
Test Passed
<img width="1280" alt="screen shot 2017-05-15 at 18 19 35" src="https://cloud.githubusercontent.com/assets/12330493/26064942/175704de-399b-11e7-84de-da021b9b83f0.png">
