### ISSUE TITLE
Animation is not shown in 404 not found page

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#122]
![screen shot 2017-05-16 at 10 52 02 am](https://cloud.githubusercontent.com/assets/18532617/26095607/df1e25e8-3a26-11e7-8b03-6b50a3776757.png)

**Comment by avozicov** [comment]
Test Failed.
Styles for "404 Not Found Page" are broken on Safari browser.
_Please refer to attachments for more details:_
<img width="1280" alt="screen shot 2017-05-18 at 15 08 44" src="https://cloud.githubusercontent.com/assets/12330493/26201557/44d18b3a-3bdc-11e7-91a9-b0be68c27757.png">

**Comment by avozicov** [comment]
Defect checking status = Passed
 
<img width="1280" alt="screen shot 2017-05-19 at 16 24 23" src="https://cloud.githubusercontent.com/assets/12330493/26249539/afb43802-3caf-11e7-9ff9-8e5fc3d578ab.png">
<img width="1280" alt="screen shot 2017-05-19 at 16 24 27" src="https://cloud.githubusercontent.com/assets/12330493/26249540/afb8528e-3caf-11e7-9cb8-a61d2f5e16b5.png">
