### ISSUE TITLE
Responsive issues 

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#123]
![screen shot 2017-05-16 at 11 24 20 am](https://cloud.githubusercontent.com/assets/18532617/26097727/2a66a0d2-3a2e-11e7-8795-75acca9aed9f.png)

![screenshot_2017-05-16-08-26-26_com android chrome](https://cloud.githubusercontent.com/assets/18532617/26097798/5f033fa8-3a2e-11e7-94e3-5c8fcaec8fd7.png)

**Comment by avozicov** [comment]
<img width="743" alt="screen shot 2017-05-18 at 15 13 54" src="https://cloud.githubusercontent.com/assets/12330493/26201634/aa7c2e18-3bdc-11e7-9912-cdb0af20df40.png">
<img width="741" alt="screen shot 2017-05-18 at 15 13 47" src="https://cloud.githubusercontent.com/assets/12330493/26201635/aa7cc0bc-3bdc-11e7-98c6-93a79f6e2650.png">
