### ISSUE TITLE
Create pop-up for Get Price in Coworking Page 

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#130]
1. Add MailChimp for Individual and Business buttons Get Price
2. Change inputs shapes of Book a tour page (according the new design in coworking page (pop-up) )

**Comment by avozicov** [comment]
**Test Failed**
- "Subscription" button became broken after submitting form request on "individual" plan
- "Subscription" button is missing on business plan as a result the form can not be submitted
- Romanian english is set as a default language when submitting "Book a Tour" request in spite the fact that english language was selected as option (expected result - display the notification message according the selected option on request submit) 

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-05-31 at 15 24 17" src="https://cloud.githubusercontent.com/assets/12330493/26631762/4ba7b9aa-4615-11e7-817d-42b68ff7538d.png">

<img width="1280" alt="screen shot 2017-05-31 at 15 16 42" src="https://cloud.githubusercontent.com/assets/12330493/26631614/99b26178-4614-11e7-8364-4b300abb696d.png">

**Comment by tkaciuk** [comment]
@avozicov  Romanian english is set as a default language ... is not for testing

**Comment by avozicov** [comment]
The following implementation is required to be improved:
- Increase the modal height value so the "Subscribe" button will be visible 
- "First Name" field is seems to be wrong, because "Last Name" field is missing (Rename to "Full Name" can be implemented as solution)

Please refer to attachment for actual result:
<img width="1280" alt="screen shot 2017-06-02 at 17 39 12" src="https://cloud.githubusercontent.com/assets/12330493/26730789/c598de46-47ba-11e7-9b6e-6205ee6aa37d.png">

**Comment by avozicov** [comment]
**Test Passed**
- all items from comment above has been implemented
_Please refer to attachment for more details:_

<img width="318" alt="screen shot 2017-06-07 at 14 59 08" src="https://user-images.githubusercontent.com/12330493/26877262-ff7ca996-4b91-11e7-9651-a44ffb4d4160.png">
<img width="575" alt="screen shot 2017-06-07 at 14 59 16" src="https://user-images.githubusercontent.com/12330493/26877261-ff76a3b6-4b91-11e7-9470-ff081acf38cd.png">

**Comment by avozicov** [comment]
Confirmation email screenshot:
<img width="791" alt="screen shot 2017-06-07 at 15 02 21" src="https://user-images.githubusercontent.com/12330493/26877387-731855b2-4b92-11e7-9a63-86e674fa74aa.png">
