### ISSUE TITLE
New embedded post in gallery broken styles 

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#132]
![screen shot 2017-05-29 at 11 00 18 am](https://cloud.githubusercontent.com/assets/18532617/26541413/385cb372-445e-11e7-9ec6-f9a7c20d74f6.png)

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="2017-05-29 18 00 59" src="https://cloud.githubusercontent.com/assets/12330493/26554446/c89ac278-4498-11e7-993a-5addb28759ea.png">
