### ISSUE TITLE
Missing npm install commands

### ISSUE THREAD

**Issue by eistrati** [404md/www#142]
Build and deploy scripts are using external tools that are NOT installed by default. Previous version of build script included corresponding `npm install` commands, but for some unknown reason they have been removed. Please update `build.sh` script to include as an option those install commands.

**Comment by ddimitrioglo** [comment]
They were commented earlier
![image](https://cloud.githubusercontent.com/assets/9005667/26650048/dd8ba666-4650-11e7-93bd-e97605f805ad.png)
so I have removed them at all, but included them into Pre-requisites block in project's [readme](https://github.com/404md/www/blob/dev/README.md) 

@eistrati do I need to revert the changes?

**Comment by eistrati** [comment]
I think we need to add them as an option and ask user "Would like to install npm dependencies?"

**Comment by ddimitrioglo** [comment]
Got it, thanks.

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- There should be an option with the text "Would like to install npm dependencies? [y|n]:" when user executing "sh deploy.sh [env]" command from project directory 
<img width="622" alt="screen shot 2017-06-08 at 15 34 42" src="https://user-images.githubusercontent.com/12330493/26928833-3e83c75e-4c60-11e7-8e14-9ddc1901f6eb.png">
