### ISSUE TITLE
Change inputs shapes of Contact page (according the new design )

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#145]
![screen shot 2017-06-02 at 1 30 53 pm](https://cloud.githubusercontent.com/assets/18532617/26722250/caaeb2a2-4797-11e7-887e-774c32610f7c.png)

**Comment by avozicov** [comment]
**Test Passed**
<img width="444" alt="screen shot 2017-06-07 at 14 48 35" src="https://user-images.githubusercontent.com/12330493/26876803-7c97d3a8-4b90-11e7-8614-4c19088b65dc.png">
