### ISSUE TITLE
Add new media link to Media page

### ISSUE THREAD

**Issue by ursuvlad** [404md/www#148]
Add the following link http://coworking.md/coworking/404-not-found/ to Media page (https://www.404.md/media/)

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-06-07 at 14 52 49" src="https://user-images.githubusercontent.com/12330493/26876944-01045440-4b91-11e7-85dd-0aae55fb77ec.png">
