### ISSUE TITLE
Add visual separation "footer" from "body" container 

### ISSUE THREAD

**Issue by avozicov** [404md/www#152]
_Enhancement:_
- Add "light-grey" color to add visual separation between "footer" and "body" containers 

                                    **Actual Result:**

<img width="1280" alt="screen shot 2017-06-09 at 18 35 01" src="https://user-images.githubusercontent.com/12330493/26982846-69f39b98-4d42-11e7-8090-4d3e7c974750.png">

                                  **Expected Result:**

<img width="1280" alt="screen shot 2017-06-09 at 18 32 53" src="https://user-images.githubusercontent.com/12330493/26982855-70043358-4d42-11e7-875c-6029f1f6ac4e.png">

**Comment by pleshco** [comment]
@avozicov Thank you for your feedback. I appreciate it very much! 
FYI now I'm working on the similar task - https://github.com/MitocGroup/www/issues/162
