### ISSUE TITLE
Change background image on "home" page by using a higher quality image

### ISSUE THREAD

**Issue by avozicov** [404md/www#153]
**Enhancement:**
- A higher quality image is required to be used as the actual one is low quality and pixels can be seen in image 

- As a option use the same image but with higher quality or replace with the new one which meets overall website design 

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-06-09 at 18 38 49" src="https://user-images.githubusercontent.com/12330493/26983154-7f51baaa-4d43-11e7-8703-ffdea530078f.png">

**Comment by pleshco** [comment]
@avozicov Thank you once again! I will plan it as a task for 404 design evolution.
