### ISSUE TITLE
Change behavior on "Book a tour" form submit

### ISSUE THREAD

**Issue by avozicov** [404md/www#154]
_Actual Result:_
- Once the required fields are filed with the data and form submit is submitted, notification message appears at the bottom of the form and fields became empty (attachment 1)

_Enhancement:_
- On form submitting hide all the fields and display "Thank you" page template with the informative text 
- Add "return" button so user can return and submit the form again with the different request data
- Styles, colors and fonts for all described functionality are required to meet overall site design 
<img width="1280" alt="screen shot 2017-06-09 at 18 46 56" src="https://user-images.githubusercontent.com/12330493/26983504-b0ec54d4-4d44-11e7-8b63-6966f0339d77.png">

**Comment by mcuclev** [comment]
![image](https://user-images.githubusercontent.com/35545331/38049778-c20a6418-32d1-11e8-997d-304f1d3c28d7.png)
Book A Tour form's appearance in the web-boost-based version. 

#155 analogical comment concerning the confirmation page; a user can navigate from the confirmation page with help of the menu in the header.

**Comment by avozicov** [comment]
Test **Passed**
<img width="993" alt="screen shot 2018-04-18 at 18 34 33" src="https://user-images.githubusercontent.com/12330493/38942365-3ff0313a-4337-11e8-9a97-1ff339050937.png">

**Comment by eistrati** [comment]
Checked.
