### ISSUE TITLE
Change the language option on "Book a tour" form submitting

### ISSUE THREAD

**Issue by avozicov** [404md/www#155]
_Actual result:_
- Once user submitted the request on "Book a tour" page,  notification message is displayed in "romanian" language by default, even if user selected "russian" or "english" option 

_Enhancement 1 :_
-  Display "notification message" on the language which was previously selected by user on form submitting 

In case when:
- Enhancement one can not be applied => remove language selector option as this causes negative user experience

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-06-09 at 18 46 52" src="https://user-images.githubusercontent.com/12330493/26983788-a41def96-4d45-11e7-88db-9c5e534fbad2.png">
<img width="1280" alt="screen shot 2017-06-09 at 18 46 56" src="https://user-images.githubusercontent.com/12330493/26983787-a41b12e4-4d45-11e7-8a5c-0de29e9ed876.png">

**Comment by mcuclev** [comment]
In the web-boost-based version (currenly in "_dev" branch), once filled out and submitted, Book A Tour form redirects you to a confirmation page, which is localised for every language option available on the website.
![image](https://user-images.githubusercontent.com/35545331/38049545-32723ba0-32d1-11e8-975a-9e752e937e2b.png)
![image](https://user-images.githubusercontent.com/35545331/38049563-3cdb7304-32d1-11e8-9bba-d26671460595.png)
![image](https://user-images.githubusercontent.com/35545331/38049580-4889cc6e-32d1-11e8-87f1-6fcb8df3332e.png)

**Comment by eistrati** [comment]
Checked.
