### ISSUE TITLE
Improve "Get in touch" form submitting 

### ISSUE THREAD

**Issue by avozicov** [404md/www#156]
_Enhancement:_
- Once request is submitted fields should became empty and notification message should be displayed 
- Use text which will notify user on successful form submitting and use fonts and color which will meet overall website design 

_Please refer to attachment for actual result:_ 
<img width="1280" alt="screen shot 2017-06-09 at 19 11 12" src="https://user-images.githubusercontent.com/12330493/26984267-6dde95f0-4d47-11e7-952a-b2b2232a9af3.png">

**Comment by mcuclev** [comment]
In the web-boost-based version (currenly in "_dev" branch), once filled out and submitted, Contact form redirects you to a confirmation page, which is localised for every language option available on the website.
![image](https://user-images.githubusercontent.com/35545331/38048350-c586c9f0-32cd-11e8-844d-cf49264885fb.png)
![image](https://user-images.githubusercontent.com/35545331/38048381-ddc1f954-32cd-11e8-8e30-e910e00912d3.png)
![image](https://user-images.githubusercontent.com/35545331/38048399-edc11b78-32cd-11e8-9192-8e9abd61f143.png)

**Comment by ddimitrioglo** [comment]
@avozicov moving into review/QA as requirements have changed

**Comment by avozicov** [comment]
Experienced the issue with form submitting.
Described here https://github.com/404md/www/issues/223

**Comment by avozicov** [comment]
I am experiencing broken css issue on `message` field while submitting the request.
Let's fix it in terms of this ticket ;)

<img width="403" alt="screen shot 2018-04-18 at 18 28 44" src="https://user-images.githubusercontent.com/12330493/38942149-c49163b0-4336-11e8-8694-df3816145ea7.png">

**Comment by eistrati** [comment]
Checked.
