### ISSUE TITLE
Calendar for The big meeting room (ocean room)

### ISSUE THREAD

**Issue by ursuvlad** [404md/www#162]
Please add a page www.404.md/oceanroom with the following calendar (do not include it in the menu)

<iframe src="https://calendar.google.com/calendar/embed?src=pycoding.biz_q2ekr439bpo0tgdurmu01m9uh8%40group.calendar.google.com&ctz=Europe/Chi
sinau" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-06-21 at 17 45 29" src="https://user-images.githubusercontent.com/12330493/27390350-b2f58d0e-56a9-11e7-97c7-ec049908b6a8.png">
<img width="1280" alt="screen shot 2017-06-21 at 17 45 33" src="https://user-images.githubusercontent.com/12330493/27390348-b2f4a4d4-56a9-11e7-8a8a-20e32f79b1ae.png">
<img width="1280" alt="screen shot 2017-06-21 at 17 46 41" src="https://user-images.githubusercontent.com/12330493/27390349-b2f48b7a-56a9-11e7-8dc1-6d7f0fc2eb77.png">

**Comment by ursuvlad** [comment]
Please change the link from www.404.md/oceanroom to www.404.md/giurgiulesti

Add 2 more calendars:

1. www.404.md/criva

<iframe src="https://calendar.google.com/calendar/embed?src=pycoding.biz_s5ihf9jrelv861s5aem6fh03qo%40group.calendar.google.com&ctz=Europe/Chisinau" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

2. www.404.md/Naslavcea
<iframe src="https://calendar.google.com/calendar/embed?src=pycoding.biz_8lbtf69e6c6nc7fqhgisf0re5k%40group.calendar.google.com&ctz=Europe/Chisinau" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by avozicov** [comment]
**Test Passed**
Requirements provided by @ursuvlad were implemented and works as expected 
<img width="1280" alt="screen shot 2017-06-23 at 19 52 31" src="https://user-images.githubusercontent.com/12330493/27492152-cd8509e2-584d-11e7-82dd-cfeee06582e5.png">
<img width="1280" alt="screen shot 2017-06-23 at 19 53 12" src="https://user-images.githubusercontent.com/12330493/27492150-cd80f82a-584d-11e7-9964-d8a2c96193af.png">
<img width="1280" alt="screen shot 2017-06-23 at 19 52 52" src="https://user-images.githubusercontent.com/12330493/27492151-cd84a272-584d-11e7-862b-6831c1b5193d.png">

**Comment by avozicov** [comment]
There is an use case when accessing [](https://www-dev.404.md/oceanroom/) it points to .../giurgiulesti calendar 
Expected to see 404 not found page cause link should not be valid anymore 

@ddimitrioglo 
This is related to aws cache?

**Comment by ddimitrioglo** [comment]
@avozicov Fixed

**Comment by avozicov** [comment]
@ddimitrioglo Thank you!
**Test Passed**
<img width="1280" alt="screen shot 2017-06-26 at 11 57 21" src="https://user-images.githubusercontent.com/12330493/27531818-ad2dfc7e-5a66-11e7-8f46-521d5ad479f5.png">
