### ISSUE TITLE
Change FontAwesome to Material Icons

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#169]
![screen shot 2017-07-17 at 5 00 51 pm](https://user-images.githubusercontent.com/18532617/28271571-91fea514-6b11-11e7-90de-a45589184821.png)

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-25 at 16 03 11" src="https://user-images.githubusercontent.com/12330493/28573264-ca619992-7152-11e7-98e7-7a67968515f1.png">
