### ISSUE TITLE
Change 404 not found page

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#170]
https://xd.adobe.com/view/ff5e3511-5eab-40e9-9916-e037b0ddbbe4/screen/9c320f10-4a56-447e-903a-4783e18ac207/404/

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-25 at 16 03 57" src="https://user-images.githubusercontent.com/12330493/28573295-e6b825b6-7152-11e7-8fbd-09c66cae0d85.png">
