### ISSUE TITLE
New Home page style

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#172]
https://xd.adobe.com/view/ff5e3511-5eab-40e9-9916-e037b0ddbbe4/

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-25 at 16 06 01" src="https://user-images.githubusercontent.com/12330493/28573424-4bc51b12-7153-11e7-940d-c690802888d9.png">
<img width="1280" alt="screen shot 2017-07-25 at 16 06 03" src="https://user-images.githubusercontent.com/12330493/28573425-4bcc96d0-7153-11e7-88a1-ae1edb31d1b1.png">
