### ISSUE TITLE
Add one more contact number

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#183]
078 360 009

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-08-02 at 16 04 15" src="https://user-images.githubusercontent.com/12330493/28874878-537be9fe-779c-11e7-95d8-a8c09fdadbfc.png">

**Comment by tkaciuk** [comment]
078 360 009 
- The contact number has been deleted

**Comment by avozicov** [comment]
Test **Passed**
- 078 360 009 removed
<img width="440" alt="screen shot 2017-09-08 at 16 22 06" src="https://user-images.githubusercontent.com/12330493/30213527-f2bd76ea-94b1-11e7-916c-a3be20ce524c.png">
