### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by pleshco** [404md/www#186]
Make an event page with Facebook events and meeting rooms pricing based on the following design - https://xd.adobe.com/view/92f47ef5-e518-4441-bce7-576bd1a2efb0/screen/283d533a-1abe-4da8-aecc-bb9d444e5d0d/events

- Last 6 Facebook events parsing with following info:
1. Event picture
2. Event title
3. Event date and time
5. Event link

**Comment by tkaciuk** [comment]
@ursuvlad To implement this task i need backend support (fetch Facebook event list through api)
