### ISSUE TITLE
Add transitions and animation to variety of elements

### ISSUE THREAD

**Issue by pleshco** [404md/www#188]

**Comment by tkaciuk** [comment]
- Parallax scrolling effect (image in the top)
- Transition for all links
- Magic line for navigation navbar

**Comment by avozicov** [comment]
Test **Passed**
Parallax scrolling effect (image in the top) 
- Can be tested by scroll the pages

Transition for all links
- Can be tested by hover actions on available links 

Magic line for navigation navbar
- Can be tested by navigating between top menu links
