### ISSUE TITLE
Change icons on Coworking page

### ISSUE THREAD

**Issue by pleshco** [404md/www#189]
https://drive.google.com/open?id=0B7hnROLVlCNIZUMwRWcwdXBBdms

**Comment by avozicov** [comment]
Test Execution is blocked by the broken Coworking page
<img width="1280" alt="screen shot 2017-09-08 at 16 10 06" src="https://user-images.githubusercontent.com/12330493/30213464-c6a79b8a-94b1-11e7-9762-8bae7c75f246.png">

**Comment by avozicov** [comment]
Test **Passed**
<img width="1364" alt="screen shot 2017-09-19 at 10 38 21 am" src="https://user-images.githubusercontent.com/12330493/30580849-b3a3b6e0-9d26-11e7-9085-587070f9c293.png">
