### ISSUE TITLE
Members page

### ISSUE THREAD

**Issue by pleshco** [404md/www#195]
Rebuild Members page according to the following design - https://xd.adobe.com/view/92f47ef5-e518-4441-bce7-576bd1a2efb0/screen/bdf5764c-5b90-4d54-bbc4-938b08d8857f/members/

**Comment by pleshco** [comment]
ImpacT - http://impactacademies.com/ru/home

EN:
ImpacT Academies & Camps was created to give children the ability to get the digital skills needed to turn them from consumers to technological creators. Even if the child in the future will not activate in this sphere, these skills will help him achieve success in the contemporary world.
 
Using our own educational program, adapted from Silicon Valley schools, we teach not only technical skills - graphic design, programming, web sites, games, robotics, but also personal development skills: ability to manage time correctly, presentation skills , persuasion, negotiation, and others.
 
We are glad to extend the horizon of opportunities to the next generation, providing the skills needed to become a leader in the digital age.
Join our trip!

RU: 
ImpacT Academies & Camps основана для предоставления возможности нашим детям получить необходимые навыки и обучить их цифровой грамотности с целью перейти со стадии потребителя технологий в их создателя. Даже если ребенок не станет работать в этой сфере, без таких способностей почти невозможно будет добиться успеха в современном мире. 

Используя собственную учебную программу, адаптированную из школ Силиконовой долины, мы обучаем не только техническим навыкам – графическому дизайну, программированию, разработке сайтов, игр, робототехнике, но и soft-skills направленных на управление личным развитием, умению грамотно управлять своим временем, умению убеждать, навыкам ведения переговоров и т.д.

Мы рады расширить возможности будущего поколения, предоставив им все нужные навыки чтобы стать лидерами в цифровую эру. Присоединяйтесь к нашему путешествию!

 RO:
ImpacT Academies & Camps a fost creat pentru a oferi posibilitatea copiilor să obțină abilități digitale necesare pentru a îi transforma din consumatori în creatori tehnologici. Chiar dacă copilul în viitor nu va activa în această sferă, aceste abilități îl vor ajuta obțină succes în lumea contemporană.

Folosind programul educațional propriu, adaptat din școlile din Sillicon Valley, noi predăm nu doar abilități tehnice - design grafic, programare, create website-urilor, jocurilor, robotica, dar și abilități de dezvoltare personală: capacitatea de a administra corect timpul, abilități de prezentare, de convingere, de negociere și altele.

Noi suntem bucuroși să îi extindem orizontul oportunităților generației viitoare, oferind abilitățile necesare pentru a deveni leader în epoca digitală. 
Alăturați-vă călătoriei noastre!

**Comment by pleshco** [comment]
iELLO IT - http://www.iello.ro/

EN:
iELLO is an international IT solutions provider specialized in software development and SOA integration that provide organizations with unprecedented agility, scalability, interoperability, features and performance.
 
iELLO is proud of the self-assumed pioneering role as a SOA integration solutions provider in the region, based on a 100% enterprise class open source middleware platform from WSO2.
 
Out team has built an excellent reputation by implementing the most challenging projects and by promptly supporting our customers either during implementations or production support.
 
iELLO’s agility is supported by the extensive knowledge and expertise of the team that enable us to respond to customer requirements in a commercial challenging and technical competitive environment.


RU:
iELLO - это международный провайдер IT решений, специализирующийся на программной разработке и SOA интеграции, которые предоставляют организациям беспрецедентную гибкость, масштабируемость, совместимость и производительность.

iELLO гордится ролью первопроходца в предоставлении услуг по SOA интеграции в регионе, базируясь на 100% платформе промежуточного ПО с открытым исходным кодом корпоративного класса от WSO2.

Наша команда создала великолепную репутацию, реализуя самые сложные проекты и предоставляю оперативную поддержку наших клиентов, как на этапе реализации, так и на этапе производства. 

Маневренность iELLO обеспечивается обширными знаниями и опытом команды, которые позволяют нам реагировать на требования клиентов в коммерчески-сложной и технически-конкурентной среде.


RO:
iELLO este un furnizor de soluții IT internaționale specializat în dezvoltarea de software și integrarea SOA care oferă organizațiilor agilitate, scalabilitate, interoperabilitate, caracteristici și performanță fără precedent.
 
iELLO este mândră de rolul de pionierat auto-asumat ca furnizor de soluții de integrare SOA în regiune, bazat pe o platformă de middleware de 100% din clasa enterprise open source de la WSO2.
 
Echipa noastră și- a construit o reputație excelentă prin implementarea celor mai dificile proiecte și prin sprijinirea rapidă a clienților noștri, fie în timpul implementărilor, fie prin suportul de producție.
 
Agilitatea companiei iELLO este susținută de cunoștințele și expertiza extinsă ale echipei care ne permit să răspundem cerințelor clienților într-un mediu concurențial competitiv și tehnic.

**Comment by pleshco** [comment]
iELLO logo - https://drive.google.com/open?id=0B7hnROLVlCNIZjVFU2tYYVV5Slk
ImpacT logo - https://drive.google.com/open?id=0B7hnROLVlCNISDE5RXZjMWN6Ykk

**Comment by avozicov** [comment]
Test **Passed**
<img width="1280" alt="screen shot 2017-09-11 at 12 29 58" src="https://user-images.githubusercontent.com/12330493/30268084-3aed527c-96ed-11e7-89eb-db22be4282cb.png">
