### ISSUE TITLE
Change link to Google maps

### ISSUE THREAD

**Issue by pleshco** [404md/www#196]
Change link to Google maps in footer and on the 404 page to following:

https://goo.gl/maps/7MArc7ukMhq

**Comment by avozicov** [comment]
Test **Passed**
Changed to 404 instead of Olimpiada
<img width="1280" alt="screen shot 2017-09-11 at 12 26 14" src="https://user-images.githubusercontent.com/12330493/30267838-7fdd5de2-96ec-11e7-883f-ea31a49cb12a.png">
