### ISSUE TITLE
Change next\prev buttons in all the carousels 

### ISSUE THREAD

**Issue by pleshco** [404md/www#201]
Change next\prev buttons in all the carousels:

- members page
- events page

**Comment by avozicov** [comment]
Test **Passed**
<img width="1254" alt="screen shot 2017-09-19 at 10 44 14 am" src="https://user-images.githubusercontent.com/12330493/30581065-889067cc-9d27-11e7-96ac-a6ed6dd936e8.png">
<img width="1280" alt="screen shot 2017-09-19 at 10 43 34 am" src="https://user-images.githubusercontent.com/12330493/30581069-8b3ab1f8-9d27-11e7-92c5-c1f74e1bd866.png">
