### ISSUE TITLE
Fix time on Events page

### ISSUE THREAD

**Issue by pleshco** [404md/www#204]
time is displayed incorrect (probabli in GMT)
![screen shot 2017-09-19 at 10 19 44](https://user-images.githubusercontent.com/25935288/30580113-160159da-9d24-11e7-900e-62497bb98912.png)

**Comment by avozicov** [comment]
Test **Passed**
Event time from cover picture coincides with retrieved time by Lambda 
<img width="1440" alt="screen shot 2017-09-20 at 15 25 34" src="https://user-images.githubusercontent.com/12330493/30643589-3e38c18c-9e18-11e7-86b1-5553ddda9a31.png">
