### ISSUE TITLE
Confirmation message should be localized

### ISSUE THREAD

**Issue by AlexandrUrita** [404md/www#214]
Steps to reproduce:

All confirmation messages should be displayed in language that is setup site.
Currently confirmation messages are displayed in Romanian

**Comment by mcuclev** [comment]
#155 #156 
Analogical comment about the confirmation page.

**Comment by avozicov** [comment]
Test execution is blocked by https://github.com/404md/www/issues/223#issuecomment-381949780

**Comment by avozicov** [comment]
Test **Passed** for rus rom eng languages

**Comment by eistrati** [comment]
Checked.
