### ISSUE TITLE
Submit form is not working for RO/RU language

### ISSUE THREAD

**Issue by AlexandrUrita** [404md/www#223]
Steps to reproduce:
1. Navigate to 404.md
2. Navigate to Contact page
3. Swithc language to RO / RU
4. Fill all fields
5. Click on Send button

Expected result: Confirmation page should be displayed

Actual result: Error message is displayed
![screen shot 2017-11-10 at 15 09 38](https://user-images.githubusercontent.com/27765884/32659923-696aaca6-c629-11e7-9b7f-fbca8176d079.png)

**Comment by mcuclev** [comment]
#156 analogical comment about the confirmation page. It is available for the forms in any language listed as an option on the website.

**Comment by avozicov** [comment]
Test **Failed**

Could not sent request using 'Contact Form'

**Comment by avozicov** [comment]
Fix for sending the request and notification message was successfully applied, but I am still experiencing broken css issue on `message` field while submitting the request.

Let's fix it in terms of this ticket ;) 

<img width="403" alt="screen shot 2018-04-18 at 18 28 44" src="https://user-images.githubusercontent.com/12330493/38941991-5ce5b310-4336-11e8-9c1c-3947a4edad4e.png">

**Comment by eistrati** [comment]
Checked.
