### ISSUE TITLE
Get Price cannot be clicked on Tablet

### ISSUE THREAD

**Issue by AlexandrUrita** [404md/www#225]
Steps to reporoduce:
1. Open on Ipad -> www-dev.404.md
2. Navigate to Coworking tab
3. Locate first column with Get Price button
4. Click on Get Price button

Expected result: PopUp should be displayed with corresponded section

Actual result: Nothing happening
![screen shot 2017-11-13 at 13 30 27](https://user-images.githubusercontent.com/27765884/32723841-9d62dde4-c877-11e7-9e6f-f86ecafc251f.png)

**Comment by AlexandrUrita** [comment]
Issue is still reproducible

**Comment by tkaciuk** [comment]
After new changes this task are not valid
