### ISSUE TITLE
No limit entry for experience in year field

### ISSUE THREAD

**Issue by AlexandrUrita** [404md/www#230]
Steps to reproduce:
1. Navigate to www-dev.404.md
2. Navigate to Coworking page
3. Under Individual column click on Get Price button
4. Enter large number till end of field

Expected result: 2 digits will be ok for limit

Actual result: user can enter invalid value
<img width="1233" alt="screen shot 2017-11-22 at 09 33 42" src="https://user-images.githubusercontent.com/27765884/33115083-4372d670-cf68-11e7-9f67-4e5e9152dc5e.png">
<img width="814" alt="screen shot 2017-11-22 at 09 34 04" src="https://user-images.githubusercontent.com/27765884/33115097-568a6caa-cf68-11e7-9fad-7a167d097e9c.png">

**Comment by tkaciuk** [comment]
After new changes this task are not valid
