### ISSUE TITLE
Change text for Coworking Page

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#232]
Test Drive
24 hours -> One week

Individual

2500 MDL
- Fixed workplace;
- Access to conference rooms;
- Free access to all trainings and events;
- 24/7 biometric access;
- Coffee, tea, fruits and biscuits;
- Free 1 week invitation for 2 friends;
- Legal consulting;
- Accountant;
- Free use of projectors;
- Storage room / servers;

1500 MDL

- Fixed workplace;
- 24/7 biometric access; 
- Coffee, tea, fruits and biscuits;
- Limited access to conference rooms;

Business 

2500 MDL
For Teams up to -15%

**Comment by AlexandrUrita** [comment]
Text should be updated for notes:
Get Price should be changed to Contact Us

<img width="621" alt="screen shot 2017-11-28 at 16 41 52" src="https://user-images.githubusercontent.com/27765884/33325736-cd1fac3e-d45b-11e7-808c-b7f60c89c53f.png">
<img width="660" alt="screen shot 2017-11-28 at 16 42 03" src="https://user-images.githubusercontent.com/27765884/33325737-cd40c144-d45b-11e7-9640-67c6e7f3bbe8.png">
<img width="648" alt="screen shot 2017-11-28 at 16 42 15" src="https://user-images.githubusercontent.com/27765884/33325738-cd5eb91a-d45b-11e7-937b-c963ab5166cd.png">

**Comment by AlexandrUrita** [comment]
Task can be closed:
<img width="669" alt="screen shot 2017-11-28 at 17 09 46" src="https://user-images.githubusercontent.com/27765884/33326953-066e42ea-d45f-11e7-88e9-9a8554cf4d62.png">
<img width="685" alt="screen shot 2017-11-28 at 17 10 00" src="https://user-images.githubusercontent.com/27765884/33326954-068b6cb2-d45f-11e7-97c4-bba258852157.png">

**Comment by AlexandrUrita** [comment]
Task can be closed:
<img width="669" alt="screen shot 2017-11-28 at 17 09 46" src="https://user-images.githubusercontent.com/27765884/33326953-066e42ea-d45f-11e7-88e9-9a8554cf4d62.png">
<img width="685" alt="screen shot 2017-11-28 at 17 10 00" src="https://user-images.githubusercontent.com/27765884/33326954-068b6cb2-d45f-11e7-97c4-bba258852157.png">

**Comment by tkaciuk** [comment]
Delete Accountant from all columns

**Comment by tkaciuk** [comment]
Updates for requirements:
- Remove "Accountant" from all columns

**Comment by AlexandrUrita** [comment]
updates are applied:
<img width="1380" alt="screen shot 2017-11-29 at 18 21 57" src="https://user-images.githubusercontent.com/27765884/33385963-986a3310-d532-11e7-8e87-0a87a1edfde3.png">
