### ISSUE TITLE
Contact page is broken on PROD

### ISSUE THREAD

**Issue by AlexandrUrita** [404md/www#237]
1. Navigate to https://www.404.md/contact/
2. Check for issues on page

Expected result: Page should be fully workable, CSS style is applied, google map is workable

Actual result: Page is loaded w/o CSS styles
![screen shot 2017-12-12 at 10 54 08](https://user-images.githubusercontent.com/27765884/33875401-d2c051dc-df2a-11e7-8c3b-0aa7b20ab3fc.png)

**Comment by AlexandrUrita** [comment]
Issue resolved
![screen shot 2017-12-13 at 11 00 32](https://user-images.githubusercontent.com/27765884/33930245-e6dac42a-dff4-11e7-9843-936c201faf93.png)

**Comment by eistrati** [comment]
Checked.
