### ISSUE TITLE
Google map is not working on Contact page (Dev)

### ISSUE THREAD

**Issue by AlexandrUrita** [404md/www#238]
1. Navigate to https://www-dev.404.md/contact/
2. Check for google map next to contact form

Expected result: Google map should be showing location

Actual result: Google map is not available
![screen shot 2017-12-12 at 10 58 46](https://user-images.githubusercontent.com/27765884/33875616-763e6c86-df2b-11e7-85b8-f98edde68ff3.png)

**Comment by AlexandrUrita** [comment]
Issue resolved:
![screen shot 2017-12-13 at 11 04 51](https://user-images.githubusercontent.com/27765884/33930514-d3216992-dff5-11e7-815c-5d4e3181bde2.png)

**Comment by ursuvlad** [comment]
Duplicate https://github.com/404md/www/issues/240
