### ISSUE TITLE
  Google map is not showing on contact page

### ISSUE THREAD

**Issue by AlexandrUrita** [404md/www#240]
Steps to reproduce:
1. Navigate to www.404.md
2. Navigate to Contact page

Expected result: Google map should be loaded and fully workable

Actual result: Google map is unavailable![Screen Shot 2018-01-15 at 10.57.58.png](https://images.zenhubusercontent.com/58f86b8b51aa2c30577beb5e/0e6b2f6c-23b9-44d7-b5f2-fdeb09fd1796)

**Comment by avozicov** [comment]
Test **Failed**
- Google map is not working for latest **dev** & **prod** environments after latest deploy 

Issue is reproducing with the same steps as described in ticket

**Comment by mcuclev** [comment]
Fixed in the new web-boost-based version (currently "_dev" branch).
![image](https://user-images.githubusercontent.com/35545331/38051078-dec07af8-32d5-11e8-90ab-1f61579674c0.png)

**Comment by avozicov** [comment]
Confirm.
Test **Passed**

**Comment by eistrati** [comment]
Checked.
