### ISSUE TITLE
Price is not calculating automatically

### ISSUE THREAD

**Issue by AlexandrUrita** [404md/www#245]
Steps to reproduce:
1. Navigate to www-dev.404.md
2. Click on the Pricing
3. Scroll down till Column Teams
4. Click on + sign

Expected result: Number should be increased, price should be changed

Actual result: Number increased. Price is not changing
![Screen Shot 2018-01-30 at 18.38.10.png](https://images.zenhubusercontent.com/58f86b8b51aa2c30577beb5e/d34a6118-3861-4c5f-8db4-f2da6bca2e0c)

**Comment by AlexandrUrita** [comment]
Fixed and checked:
![screen shot 2018-01-31 at 17 23 00](https://user-images.githubusercontent.com/27765884/35630996-6f19d10a-06ab-11e8-968d-598d6d57121e.png)

**Comment by eistrati** [comment]
Checked.
