### ISSUE TITLE
New place for language icons on responsive page

### ISSUE THREAD

**Issue by AlexandrUrita** [404md/www#247]
Steps to reproduce:
1. Navigate to www-dev.404.md (on mobile device)
2. Open web page and squeeze page till responsive
3. Check for language icons for both pages

Expected result: Language icons should be moved to the footer

Actual result: No padding between icons and menu icon. 
![Screen Shot 2018-01-30 at 18.48.38.png](https://images.zenhubusercontent.com/58f86b8b51aa2c30577beb5e/8bb6fa53-a3eb-4e3a-99cb-48b3f353bd74)
![Screen Shot 2018-01-30 at 18.48.49.png](https://images.zenhubusercontent.com/58f86b8b51aa2c30577beb5e/2283e7ad-efec-4564-999d-07da1275e7f1)

**Comment by mcuclev** [comment]
![capture](https://user-images.githubusercontent.com/35545331/38023675-a3d2384a-328b-11e8-87ac-0f0fb332e474.PNG)

The issue is fixed for web responsive viewing in the web-boost-based version.

**Comment by avozicov** [comment]
Test **Passed**
<img width="333" alt="screen shot 2018-04-17 at 13 59 52" src="https://user-images.githubusercontent.com/12330493/38865826-b09c9cca-4247-11e8-904e-1c92b4790093.png">

**Comment by eistrati** [comment]
Checked.
