### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#250]
General Changes

Price Page 

Hub Resident                                         
  2500MDL
-Fixed workplace
-Free access to conference rooms
-Free access to all trainings and events
-24/7 biometric access
-Coffe, tea, fruits and bisquits
-Free exposure to 404 partners
-Free 1 week invitation for 2 friends
-Free use of projectors
-Legal Consulting
-Storage room/servers

Teams
2500MDL
-Fixed workplace
-Free access to meeting rooms
-Free access to all trainings and events
-24/7 biometric access
-Coffee, tea, fruits and bisquits
-Free exposure to 404 partners
-Free tickets to Cloud Computing conferences
-Free cloud computing certification
-Legal consulting
-Storage room/servers

Day Pass
150 MDL
-Flexible workplace
-Access to conference room
-Free access to 1 training or event
-24 hours biometric acces
-Coffe, tea, fruits and bisquits

Weekdays
550 MDL/week
-Fixed workplace
-Biometric access from 9:00-18:00
-Coffe, tea, fruicts and bisquits
-Access to meeting room
-Access to trainings and events

On the first page, instead of: LOCAL COMMUNITYY. GLOBAL
PLATFORM => COWORKING SPACE. LOCAL COMMUNITY;
- In the menu bar: instead of coworking=> pricing;
- On the pricing page, adding 4 new subscriptions, and instead of
BOOK A TOUR button=> BOOK YOUR SPACE;
- Contact phone number and languages, bringing up;
- On the members page adding Mitog Group;
- Instead of 404 Not Found=>404Moldova;

**Comment by avozicov** [comment]
Test **Passed**

Acceptance Criteria:
- All items from ticket description are required to be implemented in the latest dev build

**Comment by eistrati** [comment]
Checked.
