### ISSUE TITLE
Contact and Book A Tour: submit button should be disabled by default

### ISSUE THREAD

**Issue by mcuclev** [404md/www#301]
<i>Steps to reproduce:</i>
1. Access the new web-boost-based version of the website. (Currently "_dev" branch)
1. Navigate to "Contact" or "Book A Tour" in any language.
2. Try submitting an empty form. (Click "Submit" or "Schedule your tour")
3. MailChimp's default error message "Please enter a value" is displayed in English only.

<i>Expected result:</i>
Localised error messages.

<i>Actual result:</i>
Error messages displayed only in English appear from MailChimp resource.                       

<i>Please, refer to the attachments for actual result:</i>
![Screen Shot 2018-04-03 at 5.01.41 PM.png](https://images.zenhubusercontent.com/5ab8ff6f4b5806bc2bcc65cd/220e8de2-1814-40de-a622-7e6820aecd1d)
![Screen Shot 2018-04-03 at 5.04.09 PM.png](https://images.zenhubusercontent.com/5ab8ff6f4b5806bc2bcc65cd/d5e1bd6c-d028-4699-99c1-299f87555f38)
![Screen Shot 2018-04-03 at 5.03.24 PM.png](https://images.zenhubusercontent.com/5ab8ff6f4b5806bc2bcc65cd/9be9cb3b-29ca-4b6c-8b54-315c3deeefd5)
![Screen Shot 2018-04-03 at 5.03.46 PM.png](https://images.zenhubusercontent.com/5ab8ff6f4b5806bc2bcc65cd/e872b993-39fb-4010-ae67-df47808469ae)

To avoid receiving these MailChimp error messages which are difficult to capture and translate in the project itself due to structure of the MailChimp plugin written by @ddimitrioglo, it would be wise to disable the "Submit" and "Schedule your tour" buttons until every required field is filled in.

**Comment by avozicov** [comment]
**Fixed** in contact page
**In Progress** for Book a Tour page

**Comment by avozicov** [comment]
Test **Passed**
<img width="1440" alt="screen shot 2018-05-03 at 16 48 28" src="https://user-images.githubusercontent.com/12330493/39580452-e49aee80-4ef1-11e8-9083-430b6aa411e5.png">

**Comment by eistrati** [comment]
Checked.
