### ISSUE TITLE
Contact and Book A Tour: e-mail address validation messages should be localised

### ISSUE THREAD

**Issue by mcuclev** [404md/www#302]
<i>Steps to reproduce:</i>
1. Access the new web-boost-based version of the website. (Currently "_dev" branch)
2. Navigate to "Contact" or "Book A Tour" in any language.
3. Try submitting a form with an invalid e-mail: either without @, or with an @, but without a domain.
4. MailChimp's default error message "An email address must contain a single @" or "The domain portion of the email address is invalid (the portion after the @: )" is displayed in English only.

<i>Expected result:</i>
Localised error messages.

<i>Actual result:</i>
Error messages displayed only in English appear from MailChimp resource.                       

<i>Please, refer to the attachments for actual result:</i>
![Screen Shot 2018-04-03 at 5.22.47 PM.png](https://images.zenhubusercontent.com/5ab8ff6f4b5806bc2bcc65cd/4f1abdd9-f9d0-4f66-a976-00e7a8e90736)
![Screen Shot 2018-04-03 at 5.22.54 PM.png](https://images.zenhubusercontent.com/5ab8ff6f4b5806bc2bcc65cd/1a090265-f7a3-40ab-b785-b0df478178d3)

**Comment by avozicov** [comment]
**Fixed** in latest **dev** build

<img width="275" alt="screen shot 2018-05-10 at 15 55 39" src="https://user-images.githubusercontent.com/12330493/39870606-ab512fee-546a-11e8-84e2-8cf8adec389a.png">
<img width="272" alt="screen shot 2018-05-10 at 15 55 50" src="https://user-images.githubusercontent.com/12330493/39870607-ab775ad4-546a-11e8-9c07-9a249792f35b.png">

**Comment by eistrati** [comment]
Checked.
