### ISSUE TITLE
Gallery content isn't covered with CSS styles

### ISSUE THREAD

**Issue by mcuclev** [404md/www#303]
<i>Steps to reproduce:</i>
1. Access the new web-boost-based version of the website. (Currently "_dev" branch)
2. Navigate to "Gallery" in any language.
3. View the body content.

<i>Expected result:</i>
Styled Facebook 404 Moldova albums.

<i>Actual result:</i>
Facebook 404 Moldova albums appear as plain HTML.                 

<i>Please, refer to the attachments for actual result:</i>
![screen shot 2018-04-03 at 5 34 23 pm](https://user-images.githubusercontent.com/35545331/38255754-531c3f84-3765-11e8-8fb3-495061b19d40.png)
![screen shot 2018-04-03 at 5 34 41 pm](https://user-images.githubusercontent.com/35545331/38255760-553c0e98-3765-11e8-8475-79513cf3081a.png)

In the older version of the website, the albums were pasted directly from Facebook as embedded HTML. Now, it is implemented with AWS Lambda by @Valkora.

**Comment by avozicov** [comment]
**Fixed**
<img width="376" alt="screen shot 2018-05-10 at 13 01 15" src="https://user-images.githubusercontent.com/12330493/39864436-3ea83602-5452-11e8-9cdf-cb308f387317.png">

I will mark this as passed for this time, but @mcuclev when you have some time would be great to cover the use case when text block is missing - it is expected to have the same image height for consistency ;) 

<img width="531" alt="screen shot 2018-05-10 at 13 00 52" src="https://user-images.githubusercontent.com/12330493/39864532-91ebd454-5452-11e8-8c3a-a6b861ef7b82.png">

**Comment by avozicov** [comment]
I am returning this ticket back to In Progress and will mark it as resolved once the use case above will be fixed

**Comment by avozicov** [comment]
Issue with icons is fixed but first album which is expected to be excluded is still displaying on Gallery page,
Please fix it

<img width="1440" alt="screen shot 2018-05-10 at 18 35 45" src="https://user-images.githubusercontent.com/12330493/39878544-53efb15a-5481-11e8-8321-965189f3c5cb.png">

**Comment by avozicov** [comment]
Fixed in latest **dev** build

**Comment by eistrati** [comment]
Checked.
