### ISSUE TITLE
Add `language selection` in both top and bottom `Book a Tour` form

### ISSUE THREAD

**Issue by avozicov** [404md/www#308]
<img width="1440" alt="bookatour" src="https://user-images.githubusercontent.com/12330493/38987414-56be81fe-43d8-11e8-8340-55be421a8b8b.png">

**Comment by avozicov** [comment]
**Applied**

<img width="697" alt="screen shot 2018-05-03 at 16 50 36" src="https://user-images.githubusercontent.com/12330493/39580617-385dfbca-4ef2-11e8-9d40-a29198cdd3aa.png">

**Comment by eistrati** [comment]
Checked.
