### ISSUE TITLE
Google map is not loaded on `contact` page

### ISSUE THREAD

**Issue by avozicov** [404md/www#310]
We have an issue in our **prod** environment with loading Google Map on `contact` page
To reproduce it please access the following url `http://www.404.md/contact/`

![Screen Shot 2018-04-30 at 13.03.22.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/99e43c8a-35fd-4439-a705-430194a09c76)

**Comment by avozicov** [comment]
Fix is applied in dev env
Will be fixed after deploying code to prod env

**Comment by avozicov** [comment]
Fixed in the lates production build
<img width="1440" alt="screen shot 2018-05-10 at 19 02 15" src="https://user-images.githubusercontent.com/12330493/39879884-b7dd64d4-5484-11e8-98d8-0d096ae9148d.png">

**Comment by eistrati** [comment]
Checked.
