### ISSUE TITLE
Dev environment uses files from production related bucket 

### ISSUE THREAD

**Issue by avozicov** [404md/www#320]
I am facing wrong behavior for out development environment which uses production related files and s3 bucket.

Please fix this and make sure that we have completely separated environments for system configuration and website components

<img width="1440" alt="screen shot 2018-05-04 at 12 47 33" src="https://user-images.githubusercontent.com/12330493/39622037-73697bd4-4f99-11e8-8c9f-d60b427a7134.png">

**Comment by avozicov** [comment]
**Fixed** for production env.

**Comment by eistrati** [comment]
Checked.
