### ISSUE TITLE
Error when selecting language on 'Book a Tour' form

### ISSUE THREAD

**Issue by avozicov** [404md/www#327]
Language selectors should be linked which means that when I am choosing "english" on the top selector it is expected that it will be automatically switched in the bottom selector 

Actual Result:
- I have two different statements between top and bottom language selectors 

To Reproduce it:
- choose RO version of website try to switch languages in form

Please refer to attachment for details
<img width="1440" alt="screen shot 2018-05-10 at 13 16 13" src="https://user-images.githubusercontent.com/12330493/39865299-11c6279a-5455-11e8-8e3b-999891e3da53.png">

**Comment by eistrati** [comment]
Checked.
