### ISSUE TITLE
Error for "book a tour" link for RU version of website

### ISSUE THREAD

**Issue by avozicov** [404md/www#329]
I am facing the error when trying to access "book a tour" link on main page link using RU version of website 

![Screen Shot 2018-05-10 at 15.36.47.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/25b4218e-4cb7-4358-b03b-d284c57858c7)

**Comment by avozicov** [comment]
**Fixed** in latest **dev** build

**Comment by eistrati** [comment]
Checked.
