### ISSUE TITLE
Fix Lambda which performs fetch for media content

### ISSUE THREAD

**Issue by avozicov** [404md/www#340]
I am facing the issue for our media content fetching.
To fix the production error we were forced to fix this manually but it is expected for Lambda to work it automatically without any issues and latest media content from facebook and instagram should be available on our website according scheduled time

Please refer to attachment for more details:
<img width="1440" alt="screen shot 2018-05-14 at 11 44 55" src="https://user-images.githubusercontent.com/12330493/39988026-fddc818a-576e-11e8-8aa6-e46a56ae57da.png">

**Comment by eistrati** [comment]
Checked.
