### ISSUE TITLE
Increase images quality across the page  

### ISSUE THREAD

**Issue by avozicov** [404md/www#39]
- Use high resolution images instead of low quality images
- Improvement should be implemented across the page on all components 
- Improvement should be implemented on main logo on 'Home Page'
- Improvement should be compatible with mobile version of web page

_Note :_ 
- Keep optimal ratio for source files between quality and size  
- Use svg file format on source files (to not lose the quality on image resize) 

_Acceptance Criteria :_ 
- Images and Logo should be displayed in high resolution for desktop and mobile versions of web page 

_Please refer to attachment for more details :_ 

<img width="1151" alt="screen shot 2017-02-27 at 16 18 21" src="https://cloud.githubusercontent.com/assets/12330493/23364622/78c20ae0-fd08-11e6-9417-6e36854a5127.png">
<img width="1280" alt="screen shot 2017-02-27 at 16 18 57" src="https://cloud.githubusercontent.com/assets/12330493/23364627/78e32a04-fd08-11e6-9410-7d809f001c2c.png">
<img width="1280" alt="screen shot 2017-02-27 at 16 18 28" src="https://cloud.githubusercontent.com/assets/12330493/23364624/78c47df2-fd08-11e6-865b-eb9c472cb235.png">
<img width="1149" alt="screen shot 2017-02-27 at 16 18 34" src="https://cloud.githubusercontent.com/assets/12330493/23364625/78c49120-fd08-11e6-8070-2794ce110951.png">
<img width="1278" alt="screen shot 2017-02-27 at 16 18 44" src="https://cloud.githubusercontent.com/assets/12330493/23364626/78ccb65c-fd08-11e6-9fa2-0e8b8c1bc3bf.png">
<img width="1280" alt="screen shot 2017-02-27 at 16 18 50" src="https://cloud.githubusercontent.com/assets/12330493/23364623/78c42f28-fd08-11e6-9343-8ecfc0fedf16.png">

**Comment by ivignan** [comment]
@eistrati Are you ok increasing the image quality with some impact on performance?
