### ISSUE TITLE
Implement form-handler for 'Get in Touch' module 

### ISSUE THREAD

**Issue by avozicov** [404md/www#41]
- Required fields should contain validation 
- Disable "Submit" button until all required fields are filed with valid data 
- Display user-friendly message on submitting form request 

Please refer to attachment for more details : 
<img width="345" alt="screen shot 2017-02-27 at 18 28 46" src="https://cloud.githubusercontent.com/assets/12330493/23369605/9dbdd1c8-fd1a-11e6-88b3-271e2ff88692.png">

**Comment by tkaciuk** [comment]
@avozicov is not valid anymore

**Comment by avozicov** [comment]
Task will be tested after deploy
