### ISSUE TITLE
Status code "405 Method Not Allowed" is displayed on "Contact Us" form on Submit

### ISSUE THREAD

**Issue by avozicov** [404md/www#42]
_Steps to reproduce :_ 
- Navigate to "Contact" page from top-menu 
- Click on "Submit" button 

_Bug :_ 
By clicking on "Submit" button user is redirecting to error page with the status code "405 Method Not Allowed"

_Improvement :_ 
- Disable "Submit" button until form-handler is implemented 

_Note:_ 
Implementation is blocked by task listed bellow
https://github.com/404md/www/issues/41

_Please refer to attachment for more details :_ 
<img width="1280" alt="screen shot 2017-02-27 at 18 36 51" src="https://cloud.githubusercontent.com/assets/12330493/23369994/e00de56c-fd1b-11e6-8978-0678e7e5ec68.png">

**Comment by ddimitrioglo** [comment]
- [ ] Build and deploy Contact Form lambda;
- [ ] Add form validation;
- [ ] Implement invisible captcha;
- [ ] Fix styling for error messages (Contact Form) @tkaciuk

**Comment by avozicov** [comment]
_Actual Implementation is required to be improved:_
- By click on "Submit" button "Message" field should became empty 
- Implement styles to the Notification message for successful form submit and display it on the top center of the page 
(make it visible and clear for user) 
(styles should be consistent with overall page design)

_Please refer to attachment for actual implementation:_
<img width="1280" alt="screen shot 2017-04-05 at 14 14 09" src="https://cloud.githubusercontent.com/assets/12330493/24703206/e445e2c2-1a0a-11e7-8fdb-5113d4edc083.png">
