### ISSUE TITLE
"Facebook/Slack/Instagram" links are not valid 

### ISSUE THREAD

**Issue by avozicov** [404md/www#45]
_Steps to reproduce :_
- Navigate to page-footer 
- Try to access social profiles for the following social platforms : Facebook/Slack/Instagram

_Bug :_
"Facebook/Slack/Instagram" links are not valid

**Comment by ddimitrioglo** [comment]
@avozicov Facebook - is working now.
@ivignan Can you ask IrinaP for valid links for Slack and Instagram
