### ISSUE TITLE
Remove unused area on "Terms of use" page

### ISSUE THREAD

**Issue by avozicov** [404md/www#47]
_Steps to reproduce :_
- Navigate to page-footer
- Click on "Terms of use" page

_Improvement :_
- Remove unused area on "Terms of use" page until this page is filled by required content

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-02-27 at 19 03 03" src="https://cloud.githubusercontent.com/assets/12330493/23371108/b0c33358-fd1f-11e6-9c11-bb96c81d9595.png">

**Comment by eistrati** [comment]
Use Romanian version of Terms instead of free space
