### ISSUE TITLE
Implement 'anchor' for all page components 

### ISSUE THREAD

**Issue by avozicov** [404md/www#49]
_Improvement :_
- Implement anchor for all page components to keep user focused right to the page content 
- By the click on related link user should be focused on related page content 

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-02-27 at 19 11 27" src="https://cloud.githubusercontent.com/assets/12330493/23371360/8db5ca3c-fd20-11e6-9f65-428813fcbd89.png">

**Comment by tkaciuk** [comment]
@ivignan @ursuvlad Please let me know if this "enhancement" is still valid?
We had an internal discussion with @pleshco in which he notified me about "UI" changes related to the whole website. 
Once I will get the details I will continue development actions on this issue.
Thank you in advance.
