### ISSUE TITLE
Media page on 404.md

### ISSUE THREAD

**Issue by ursuvlad** [404md/www#68]
Create a page www.404.md/media to include all the articles and videos with us from the Media. 

Alex, please create a design on how the page should look like and Irina can go further with the implementation.

Also maybe somewhere in the top to put the video from Agora  - http://agora.md/stiri/29246/video--404-not-found-la-chisinau-a-fost-deschis-un-nou-spatiu-de-co-working-destinat-companiilor-it

Here are the articles from the Media:
Agora - http://agora.md/stiri/29246/video--404-not-found-la-chisinau-a-fost-deschis-un-nou-spatiu-de-co-working-destinat-companiilor-it
CTC - https://www.facebook.com/stirilectc/videos/1860589927489436/
MYBusiness - http://mybusiness.md/ru/otkrytie-biznesa/item/5551-v-stolitse-otkrylsya-kovorking-404-not-found-foto
Realitatea - http://www.realitatea.md/---404-not-found------un-nou-spatiu-de-coworking-destinat-specialistilor-din-domeniul-it--lansat-la-chisinau--foto-_53708.html
Locals - http://locals.md/2017/v-kishinyove-otkryilsya-novyiy-it-kovorking/
Diez - http://diez.md/2017/03/10/foto-404-not-found-un-nou-spatiu-de-coworking-s-deschis-la-chisinau/
RTR - http://rtr.md/ro/stiri/tehnologie/oportunitati-de-dezvoltare-pentru-it-sti-foto
Timpul - https://www.timpul.md/articol/noi-oportunitai-de-dezvoltare-pentru-tinerii-specialiti-it-din-moldova-106159.html
Bani - http://bani.md/-404-not-found-un-spatiu-de-coworking-pentru-speciastii-it-in-cloud-computing-si-programare-va-fi-deschis-la-chisinau---89036.html

Please treat this task as a medium priority

**Comment by pleshco** [comment]
I have finished the 1st varian. https://drive.google.com/open?id=0B7hnROLVlCNIVm4tY3NsTWRoUlE

**Comment by ursuvlad** [comment]
Implement the following version - https://drive.google.com/open?id=0B7hnROLVlCNIVDlDRWwyNHJTbjQ

**Comment by avozicov** [comment]
_There is a bug founded for actual implementation:_ 
- Video is not displayed by the click 

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-04-05 at 14 10 05" src="https://cloud.githubusercontent.com/assets/12330493/24702918/94d3ef0a-1a09-11e7-8c8c-e5cc1834956a.png">
