### ISSUE TITLE
Facebook Gallery

### ISSUE THREAD

**Issue by ursuvlad** [404md/www#75]
Reference:
http://www.blastmedia.com/2013/10/11/how-to-embed-facebook-photo-album-on-a-blog/

Facebook Albums to Embed:
https://www.facebook.com/pg/404Moldova/photos/?tab=album&album_id=1809159429408845
https://www.facebook.com/pg/404Moldova/photos/?tab=album&album_id=1811400479184740
https://www.facebook.com/pg/404Moldova/photos/?tab=album&album_id=1811406442517477
https://www.facebook.com/pg/404Moldova/photos/?tab=album&album_id=1811425669182221

**Comment by avozicov** [comment]
The following embedded post is missing.
https://www.facebook.com/pg/404Moldova/photos/?tab=album&album_id=1809159429408845

@tkaciuk  Please implement all the required galleries from task description.
