### ISSUE TITLE
Add backend support for Instagram

### ISSUE THREAD

**Issue by ivignan** [404md/www#96]

**Comment by ddimitrioglo** [comment]
@ddimitrioglo:
- [x] Create Lambda to fetch user feed from Instagram;
- [x] Deploy Lambda to mitocgroup account;
- [x] Make feed data available from `www.404.md/instagram-feed.json`;
ex (for jQuery):
```
    $.ajax({
        url: '//s3.eu-central-1.amazonaws.com/www.404.md/instagram-feed.json',
        dataType: 'json'
    }).done(function (data) {
	data.forEach(function(item) {
      	console.log(item.images.url);
      })
    });
```
- [ ] Add scheduled Lambda (once a day?)

@tkaciuk 
- [ ] Init any carousel you want, to animate images;
- [ ] Adjust UI for carousel;

@ursuvlad 
- [ ] Please provide Instagram token for 404 (you can generate it here: http://instagram.pixelunion.net);

**Comment by ursuvlad** [comment]
4879135806.1677ed0.b1274b6402ce448485c32a97680e49dc

**Comment by avozicov** [comment]
@ivignan @ursuvlad 
There is an unresolved question "Add scheduled Lambda (once a day?)" 

Please let me know if we can pass it for this moment and task can be considered as "done" or I should return it in "ToDo"?
Thank you in advance

**Comment by ddimitrioglo** [comment]
Lambda scheduled for execution once a day at 10:00 UTC

**Comment by avozicov** [comment]
@ddimitrioglo got it, thank you.

**Comment by avozicov** [comment]
Confirmation testing will be performed Monday

**Comment by avozicov** [comment]
<img width="1280" alt="screen shot 2017-05-12 at 15 45 52" src="https://cloud.githubusercontent.com/assets/12330493/26001563/710ee928-3735-11e7-88dc-7ac3d4dc1184.png">
<img width="309" alt="screen shot 2017-05-12 at 17 06 20" src="https://cloud.githubusercontent.com/assets/12330493/26001561/70f2b9ec-3735-11e7-8272-c3a3e90f4725.png">
<img width="1280" alt="screen shot 2017-05-12 at 15 45 39" src="https://cloud.githubusercontent.com/assets/12330493/26001562/70f3ff82-3735-11e7-9d8b-c36ae0c334aa.png">
