### ISSUE TITLE
Add backend support for Instagram video content

### ISSUE THREAD

**Issue by tkaciuk** [404md/www#99]
- [x] Fetch Instagram video content
- [x] Fetch Images/videos description
- [x] Adjust video content in carousel (@tkaciuk)

**Comment by avozicov** [comment]
Instagram Video can not be accessed.
_Please refer to attachment for more details._
<img width="1280" alt="screen shot 2017-05-04 at 18 43 52" src="https://cloud.githubusercontent.com/assets/12330493/25712186/a34606de-30f9-11e7-91ba-41b112e3a2b6.png">

**Comment by ddimitrioglo** [comment]
@avozicov It's because someone (SashaP or Tanea) just have changed something it the video.
I re-run the lambda manually and it fixed the issue.

FYI: instagram feed fetcher runs by CRON once a day

**Comment by pleshco** [comment]
Instagram video was deleted and uploaded again several times. Hope further
our Instagram activity will be more stable. Thanks

4 мая 2017 г. 19:02 пользователь "Dmitri Dimitrioglo" <
notifications@github.com> написал:

**Comment by avozicov** [comment]
@ddimitrioglo Got it,
